export const countryCityData: { [key: string]: string[] } = {
    "India": ["Delhi", "Mumbai", "Bangalore", "Kolkata", "Chennai", "Hyderabad", "Pune", "Ahmedabad", "Jaipur", "Surat"],
    "United States": ["New York", "Los Angeles", "Chicago", "Houston", "San Francisco", "Phoenix", "San Diego", "Dallas", "San Antonio", "Philadelphia"],
    "United Kingdom": ["London", "Manchester", "Birmingham", "Liverpool", "Leeds", "Bristol", "Sheffield", "Glasgow", "Edinburgh", "Nottingham"],
    "Australia": ["Sydney", "Melbourne", "Brisbane", "Perth", "Adelaide", "Gold Coast", "Canberra", "Newcastle", "Wollongong", "Geelong"],
    "Uzbekistan": ["Tashkent", "Samarkand", "Bukhara", "Andijan", "Nukus", "Namangan", "Kokand", "Ferghana", "Gulistan", "Jizzakh"],
    "Turkmenistan": ["Ashgabat", "Turkmenabat", "Mary", "Dashoguz", "Balkanabat", "Bereket", "Bayramaly", "Tejen"],
    "Kazakhstan": ["Almaty", "Astana (Nur-Sultan)", "Shymkent", "Karaganda", "Aktobe", "Pavlodar", "Taraz", "Ust-Kamenogorsk", "Atyrau", "Kostanay"],
    "Bangladesh": ["Dhaka", "Chittagong", "Khulna", "Rajshahi", "Sylhet", "Rangpur", "Comilla", "Mymensingh", "Barisal", "Narayanganj"],
    "United Arab Emirates": ["Dubai", "Abu Dhabi", "Sharjah", "Ajman", "Al Ain", "Ras Al Khaimah", "Fujairah", "Umm Al Quwain"],
    "France": ["Paris", "Marseille", "Lyon", "Toulouse", "Nice", "Nantes", "Strasbourg", "Montpellier", "Bordeaux", "Lille"],
    "Canada": ["Toronto", "Vancouver", "Montreal", "Calgary", "Edmonton", "Ottawa", "Winnipeg", "Quebec City", "Hamilton", "Halifax"],
    "Iraq": ["Baghdad", "Basra", "Mosul", "Erbil", "Najaf", "Karbala", "Sulaymaniyah", "Kirkuk", "Ramadi", "Diwaniyah"],
    "Yemen": ["Sana'a", "Aden", "Taiz", "Mukalla", "Ibb", "Hodeida", "Al Hudaydah", "Zinjibar", "Sa'dah", "Dhamar"],
    "Oman": ["Muscat", "Salalah", "Sohar", "Nizwa", "Barka", "Sur", "Rustaq", "Ibri", "Khasab", "Shinas"],
    "Ethiopia": ["Addis Ababa", "Gondar", "Mekelle", "Dire Dawa", "Bahir Dar", "Jimma", "Hawassa", "Adama", "Harar", "Jijiga"],
    "Sudan": ["Khartoum", "Omdurman", "Port Sudan", "Nyala", "Kassala", "El Obeid", "El Fasher", "Dongola", "Sennar", "Geneina"],
    "Somalia": ["Mogadishu", "Hargeisa", "Bosaso", "Kismayo", "Baidoa", "Galkayo", "Jowhar", "Borama", "Beledweyne", "Garowe"],
    "Nigeria": ["Lagos", "Abuja", "Kano", "Ibadan", "Port Harcourt", "Benin City", "Kaduna", "Onitsha", "Jos", "Enugu"],
    "Tanzania": ["Dar es Salaam", "Dodoma", "Arusha", "Mwanza", "Mbeya", "Morogoro", "Tanga", "Tabora", "Zanzibar City", "Iringa"],
    "Turkey": ["Istanbul", "Ankara", "Izmir", "Bursa", "Antalya", "Gaziantep", "Konya", "Adana", "Mersin", "Kayseri"],
    "Nepal": ["Kathmandu", "Pokhara", "Lalitpur", "Biratnagar", "Bharatpur", "Hetauda", "Janakpur", "Nepalgunj", "Dharan", "Butwal"],
    "Bhutan": ["Thimphu", "Phuntsholing", "Paro", "Punakha", "Gelephu", "Trashigang", "Trongsa", "Wangdue Phodrang"],
    "Fiji": ["Suva", "Nadi", "Lautoka", "Labasa", "Ba", "Sigatoka", "Savusavu", "Rakiraki"],
    "Mozambique": ["Maputo", "Beira", "Nampula", "Chimoio", "Nacala", "Tete", "Quelimane", "Pemba", "Xai-Xai", "Lichinga"],
    "Angola": ["Luanda", "Lobito", "Huambo", "Benguela", "Lubango", "Kuito", "Malanje", "Namibe", "Uige", "Soyo"],
    "Kenya": ["Nairobi", "Mombasa", "Kisumu", "Nakuru", "Eldoret", "Thika", "Malindi", "Naivasha", "Kitale", "Garissa"],
    "Libya": ["Tripoli", "Benghazi", "Misrata", "Bayda", "Zawiya", "Zliten", "Al Khums", "Sabha", "Tobruk", "Ajdabiya"],
    "Tajikistan": ["Dushanbe", "Khujand", "Kulob", "Qurghonteppa", "Istaravshan", "Vahdat", "Panjakent", "Tursunzoda"],
    "Kyrgyzstan": ["Bishkek", "Osh", "Jalal-Abad", "Karakol", "Tokmok", "Naryn", "Balykchy", "Talas", "Uzgen", "Kara-Balta"],
    "Lithuania": ["Vilnius", "Kaunas", "Klaipeda", "Šiauliai", "Panevėžys", "Alytus", "Marijampolė", "Mažeikiai", "Jonava", "Utena"],
    "Jordan": ["Amman", "Zarqa", "Irbid", "Aqaba", "Russeifa", "Madaba", "Mafraq", "Salt", "Jerash", "Tafilah"]
};

export const countryCodeData = {
    "India": "+91",
    "United States": "+1",
    "United Kingdom": "+44",
    "Australia": "+61",
    "Uzbekistan": "+998",
    "Turkmenistan": "+993",
    "Kazakhstan": "+7",
    "Bangladesh": "+880",
    "United Arab Emirates": "+971",
    "France": "+33",
    "Canada": "+1",
    "Iraq": "+964",
    "Yemen": "+967",
    "Oman": "+968",
    "Ethiopia": "+251",
    "Sudan": "+249",
    "Somalia": "+252",
    "Nigeria": "+234",
    "Tanzania": "+255",
    "Turkey": "+90",
    "Nepal": "+977",
    "Bhutan": "+975",
    "Fiji": "+679",
    "Mozambique": "+258",
    "Angola": "+244",
    "Kenya": "+254",
    "Libya": "+218",
    "Tajikistan": "+992",
    "Kyrgyzstan": "+996",
    "Lithuania": "+370",
    "Jordan": "+962"
};